name: Hackathon DevRel Support Request
description: Request support from a DevRel for an upcoming hackathon.
title: "[Hackathon]: "
labels: ["hackathon"]
projects: ["adrian-d-hidalgo/3"]
body:
  - type: markdown
    attributes:
      value: |
        ## Hackathon DevRel Support Request
        Thank you for submitting your request! Please provide the details below so we can assist you effectively.

  - type: input
    id: hackathon-name
    attributes:
      label: Hackathon Name
      description: What is the name of the hackathon?
      placeholder: e.g. Global Blockchain Hackathon 2025
    validations:
      required: true

  - type: dropdown
    id: hackathon-hub
    attributes:
      label: Hackathon Hub
      description: Which hub is organizing or supporting this hackathon?
      options:
        - Hub 1
        - Hub 2
        - Hub 3
        - Hub 4
        - Other (Specify in Additional Details)
    validations:
      required: true

  - type: input
    id: hackathon-date
    attributes:
      label: Hackathon Date
      description: When will the hackathon take place? (Start and end date)
      placeholder: e.g. March 15-17, 2025
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Where will the hackathon take place? (City, Country, or Online)
      placeholder: e.g. San Francisco, USA / Virtual
    validations:
      required: true

  - type: dropdown
    id: devrel-support-needed
    attributes:
      label: Type of DevRel Support Needed
      description: What type of support do you need?
      options:
        - Technical Mentorship
        - Workshop / Talk
        - Judging
        - Documentation / Guides
        - Other (Specify in Additional Details)
    validations:
      required: true

  - type: textarea
    id: support-details
    attributes:
      label: Additional Details
      description: Provide more details on the kind of support required, expected responsibilities, and any other relevant information.
      placeholder: e.g. We need a DevRel to mentor participants on smart contract development in ICP...
    validations:
      required: true

  - type: input
    id: contact-person
    attributes:
      label: Contact Person
      description: Who should we reach out to for coordination?
      placeholder: e.g. John Doe (Email: john.doe@example.com)
    validations:
      required: true

  - type: checkboxes
    id: terms