name: DevRel Support Request
description: Request DevRel support for your activity (hackathon, startup onboarding, or training).
title: "[Support Request]: "
labels: ["support"]
projects: ["adrian-d-hidalgo/3"]
body:
  - type: markdown
    attributes:
      value: |
        ## DevRel Support Request
        Thank you for submitting your request! Please provide the details below so we can assist you effectively.

  - type: input
    id: activity-name
    attributes:
      label: Activity Name
      description: What is the name of the activity or event (hackathon, startup onboarding, etc.)?
      placeholder: e.g. Global Blockchain Hackathon 2025 or Web3 Startup Onboarding
    validations:
      required: true

  - type: input
    id: activity-date
    attributes:
      label: Activity Date
      description: When will the activity take place? (Start and end date)
      placeholder: e.g. March 15-17, 2025
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Where will the activity take place? (City, Country, or Online)
      placeholder: e.g. San Francisco, USA / Virtual
    validations:
      required: true

  - type: dropdown
    id: devrel-support-needed
    attributes:
      label: Type of DevRel Support Needed
      description: What type of support do you need?
      options:
        - Technical Mentorship
        - Workshop / Talk
        - Judging
        - Documentation / Guides
        - Other (Specify in Description)
    validations:
      required: true

  - type: textarea
    id: support-details
    attributes:
      label: Additional Details
      description: Provide more details on the kind of support required, expected responsibilities, and any other relevant information.
      placeholder: e.g. We need a DevRel to mentor participants on smart contract development in ICP...
    validations:
      required: true

  - type: input
    id: contact-person
    attributes:
      label: Contact Person
      description: Who should we reach out to for coordination?
      placeholder: e.g. John Doe (Email: john.doe@example.com)
    validations:
      required: true

  - type: dropdown
    id: timezone
    attributes:
      label: Timezone
      description: In which timezone are you located? (This helps us schedule calls and support sessions.)
      options:
        - UTC-8 (PST - Pacific Standard Time)
        - UTC-7 (MST - Mountain Standard Time)
        - UTC-6 (CST - Central Standard Time)
        - UTC-5 (EST - Eastern Standard Time)
        - UTC+0 (GMT - Greenwich Mean Time)
        - UTC+1 (CET - Central European Time)
        - UTC+5:30 (IST - Indian Standard Time)
        - UTC+8 (CST - China Standard Time)
        - UTC+9 (JST - Japan Standard Time)
        - UTC+10 (AEST - Australian Eastern Standard Time)
        - Other (Specify in Additional Details)
    validations:
      required: true

  - type: input
    id: website
    attributes:
      label: Website / Product Link (if available)
      description: Provide a link to the event's website (for hackathon) or the startup's product website.
      placeholder: e.g. https://nextgenweb3.io or https://blockchain-hackathon.com
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this request, you agree to follow our [Code of Conduct](https://example.com).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true